const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  content: ["./layout/*.liquid", "./templates/*.liquid", "./sections/*.liquid", "./snippets/*.liquid", "./assets/*.js"],
  safelist: [
    "[--swiffy-slider-item-reveal:12rem]",
    "animate-ping",
    "bg-[#ffb545]",
    "bg-gradient-radial",
    "font-thin",
    "from-seaweed-800/30",
    "icon-list-check",
    "lg:[--swiffy-slider-item-count:4]",
    "lg:[--swiffy-slider-item-count:5]",
    "max-w-[85%]",
    "md:[--swiffy-slider-item-count:3]",
    "rotate-180",
    "sm:[--swiffy-slider-item-count:3]",
    "system-serif",
    "text-right",
    "xl:[--swiffy-slider-item-count:5]",
    {
      pattern: /(bg|text|from|to)-(seafoam|seaweed|sand|shell|coral)-(100|200|300|400|500|600|700|800)/,
      variants: ["xs", "sm", "md", "lg", "hover"],
    },
    {
      pattern: /(bg|object)-(bottom|center|left|right|top)/,
      variants: ["xs", "sm", "md", "lg"],
    },
    {
      pattern: /(text|w|max-w)-(xs|sm|md|lg|xl|2xl|3xl|4xl|5xl|6xl|7xl|8xl|9xl|base)/,
      variants: ["xs", "sm", "md", "lg", "xl"],
    },
    {
      pattern: /(w|max-w|min-w|h|max-h|min-h|bottom|top|left|right|basis)-(1\/5|1\/4|1\/3|2\/5|1\/2|3\/5|2\/3|3\/4|4\/5|full|screen)/,
      variants: ["xs", "sm", "md", "lg", "xl", "2xl"],
    },
    {
      pattern: /(w|h|p|px|py|pb|pt|pl|pr|m|mx|my|mt|mb|ml|mr|bottom|top|left|right|gap|gap-x|gap-y)-(0|1|2|3|4|5|6|7|8|10|12|16|20|24|26|32|36|40|44|48|52|56|60|64|72|80|auto)/,
      variants: ["xs", "sm", "md", "lg", "xl", "2xl"],
    },
    {
      pattern: /hidden/,
      variants: ["xs", "sm", "md", "lg", "xl"],
    },
    {
      pattern: /leading-(none|tight|snug|normal|relaxed|loose)/,
      variants: ["xs", "sm", "md", "lg", "xl"],
    },
    {
      pattern: /button-(xs|sm|lg|xl|primary|secondary|tertiary|white)/,
      variants: ["xs", "sm", "md", "lg", "xl"],
    },
    {
      pattern: /tracking-(tighter|tight|normal|wide|wider|widest)/,
      variants: ["xs", "sm", "md", "lg"],
    },
    {
      pattern: /flex-(row|row-reverse|col|col-reverse)/,
      variants: ["xs", "sm", "md", "lg"],
    },
    {
      pattern: /(grid-cols|grid-rows|col-span|row-span|order)-(1|2|3|4|5|6|7|8|9|10|11|12|none)/,
      variants: ["xs", "sm", "md", "lg", "xl"],
    },
  ],
  theme: {
    colors: {
      black: "#000",
      white: "#FFF",
      transparent: "transparent",
      current: "currentColor",
      "seaweed-100": "#F6FCFA",
      "seaweed-200": "#E7F1EF",
      "seaweed-300": "#D4E1DE",
      "seaweed-400": "#A0BEB7",
      "seaweed-500": "#6E958B",
      "seaweed-600": "#497469",
      "seaweed-700": "#1D4D41",
      "seaweed-800": "#0B2E25",
      "coral-100": "#FFF9F9",
      "coral-200": "#FFEFED",
      "coral-300": "#FDDDD8",
      "coral-400": "#FFC2B9",
      "coral-500": "#FFA496",
      "coral-600": "#FF6F61",
      "coral-700": "#F55445",
      "coral-800": "#DD2715",
      "wave-100": "#F9FBFA",
      "wave-200": "#F1F5F4",
      "wave-300": "#E6ECEE",
      "wave-400": "#CAD8DD",
      "wave-500": "#A2BAC1",
      "wave-600": "#809BA5",
      "wave-700": "#607981",
      "wave-800": "#435961",
      "seafoam-100": "#F5F9F1",
      "seafoam-200": "#EDF2EB",
      "seafoam-300": "#DBE5D3",
      "seafoam-400": "#C4D5B6",
      "seafoam-500": "#B0C69F",
      "seafoam-600": "#98AE87",
      "seafoam-700": "#7B9268",
      "seafoam-800": "#627851",
      "sand-100": "#FFFEF9",
      "sand-200": "#FAF9F1",
      "sand-300": "#F4F3E7",
      "sand-400": "#E8E6CD",
      "sand-500": "#DAD6AE",
      "sand-600": "#CCC895",
      "sand-700": "#BEB97A",
      "sand-800": "#A9A35E",
      "shell-100": "#FFFCF6",
      "shell-200": "#FBF5E9",
      "shell-300": "#F5EBDE",
      "shell-400": "#E9D8C3",
      "shell-500": "#DBC09E",
      "shell-600": "#CBAB82",
      "shell-700": "#BA9763",
      "shell-800": "#A98045",
    },
    fontFamily: {
      sans: "Circular, sans-serif",
      serif: "Canela, serif",
    },
    fontWeight: {
      thin: 200,
      light: 300,
      regular: 400,
      book: 500,
      medium: 600,
      bold: 700,
      black: 800,
    },
    letterSpacing: {
      tightest: "-.075em",
      tighter: "-.05em",
      tight: "-.02em",
      normal: "0",
      slight: ".015em",
      wide: ".025em",
      wider: ".05em",
      widest: ".1em",
    },
    strokeWidth: {
      1: "1px",
      "1/25": "1.25px",
      "1/50": "1.5px",
      "1/75": "1.75px",
      2: "2px",
      "2/25": "2.25px",
      "2/50": "2.5px",
      "2/75": "2.75px",
    },
    screens: {
      "2xs": "400px",
      xs: "475px",
      ...defaultTheme.screens,
    },
    extend: {
      animation: {
        marquee: "marquee 100s linear infinite",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translate3d(0, 0, 0)" },
          "100%": { transform: "translate3d(-50%, 0, 0)" },
        },
      },
      transitionProperty: {
        height: "height",
        "max-height": "max-height",
        spacing: "margin, padding",
        "transform-opacity": "transform, opacity",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/typography"),
    function ({ addVariant }) {
      addVariant("child", "& > *");
      addVariant("child-hover", "& > *:hover");
    },
  ],
};
