const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  content: ["./layout/*.liquid", "./templates/*.liquid", "./sections/*.liquid", "./snippets/*.liquid", "./assets/global.js"],
  safelist: [
    "[--swiffy-slider-item-reveal:12rem]",
    "bg-[#ffb545]",
    "bg-bottom",
    "bg-center",
    "bg-gradient-radial",
    "bg-left",
    "bg-right",
    "bg-seafoam-100/50",
    "bg-seafoam-100",
    "bg-seafoam-200",
    "bg-seaweed-100",
    "bottom-6",
    "from-[#f3e9ea]",
    "gap-4",
    "gap-6",
    "gap-8",
    "gap-10",
    "gap-x-10",
    "gap-y-4",
    "h-40",
    "h-48",
    "h-60",
    "h-80",
    "icon-list-check",
    "leading-none",
    "left-6",
    "lg:[--swiffy-slider-item-count:4]",
    "lg:[--swiffy-slider-item-count:5]",
    "lg:bg-right",
    "lg:hidden",
    "lg:justify-center",
    "lg:max-w-lg",
    "lg:max-w-full",
    "lg:mb-4",
    "lg:min-h-[24rem]",
    "lg:pb-0",
    "lg:pb-2",
    "lg:pb-4",
    "lg:pt-8",
    "lg:px-6",
    "lg:px-8",
    "lg:text-xl",
    "max-h-[28rem]",
    "max-h-[32rem]",
    "max-h-[36rem]",
    "max-w-[85%]",
    "max-w-3/4",
    "max-w-xs",
    "max-w-sm",
    "max-w-md",
    "max-w-lg",
    "max-w-xl",
    "max-w-5xl",
    "max-w-6xl",
    "mb-4",
    "mb-8",
    "mb-12",
    "md:[--swiffy-slider-item-count:3]",
    "md:flex-row-reverse",
    "md:flex-row",
    "md:gap-6",
    "md:hidden",
    "md:max-w-md",
    "md:mb-4",
    "md:object-right",
    "md:pb-0",
    "md:pl-6",
    "md:pl-8",
    "md:px-4",
    "md:px-8",
    "md:text-xl",
    "md:text-2xl",
    "md:text-3xl",
    "md:text-5xl",
    "md:w-1/2",
    "md:w-1/3",
    "md:w-1/4",
    "md:w-2/3",
    "md:w-3/4",
    "min-h-[15rem]",
    "ml-32",
    "object-center",
    "p-6",
    "p-8",
    "pb-4",
    "pb-6",
    "pb-8",
    "pb-10",
    "pb-20",
    "pb-24",
    "pr-6",
    "pt-4",
    "pt-6",
    "pt-8",
    "px-3",
    "px-10",
    "px-12",
    "py-6",
    "py-8",
    "py-10",
    "right-6",
    "rotate-180",
    "sm:[--swiffy-slider-item-count:3]",
    "sm:hidden",
    "sm:mb-0",
    "sm:min-h-full",
    "sm:pb-0",
    "sm:pl-6",
    "sm:px-4",
    "sm:tracking-wide",
    "text-xl",
    "text-2xl",
    "text-3xl",
    "text-4xl",
    "text-5xl",
    "text-6xl",
    "to-transparent",
    "tracking-tighter",
    "tracking-widest",
    "w-16",
    "w-1/4",
    "w-1/3",
    "w-1/2",
    "w-2/3",
    "w-3/4",
    "xl:[--swiffy-slider-item-count:5]",
    "xl:hidden",
    "xl:max-w-full",
    "xl:max-w-6xl",
    "xl:pb-0",
    "xs:pl-6",
    "xs:px-8",
    "xs:tracking-tight",
  ],
  theme: {
    colors: {
      black: "#000",
      white: "#FFF",
      transparent: "transparent",
      current: "currentColor",
      "seaweed-100": "#F6FCFA",
      "seaweed-200": "#E7F1EF",
      "seaweed-300": "#D4E1DE",
      "seaweed-400": "#A0BEB7",
      "seaweed-500": "#6E958B",
      "seaweed-600": "#497469",
      "seaweed-700": "#1D4D41",
      "seaweed-800": "#0B2E25",
      "coral-100": "#FFF9F9",
      "coral-200": "#FFEFED",
      "coral-300": "#FDDDD8",
      "coral-400": "#FFC2B9",
      "coral-500": "#FFA496",
      "coral-600": "#FF6F61",
      "coral-700": "#F55445",
      "coral-800": "#DD2715",
      "wave-100": "#F9FBFA",
      "wave-200": "#F1F5F4",
      "wave-300": "#E6ECEE",
      "wave-400": "#CAD8DD",
      "wave-500": "#A2BAC1",
      "wave-600": "#809BA5",
      "wave-700": "#607981",
      "wave-800": "#435961",
      "seafoam-100": "#F5F9F1",
      "seafoam-200": "#EDF2EB",
      "seafoam-300": "#DBE5D3",
      "seafoam-400": "#C4D5B6",
      "seafoam-500": "#B0C69F",
      "seafoam-600": "#98AE87",
      "seafoam-700": "#7B9268",
      "seafoam-800": "#627851",
      "sand-100": "#FFFEF9",
      "sand-200": "#FAF9F1",
      "sand-300": "#F4F3E7",
      "sand-400": "#E8E6CD",
      "sand-500": "#DAD6AE",
      "sand-600": "#CCC895",
      "sand-700": "#BEB97A",
      "sand-800": "#A9A35E",
      "shell-100": "#FFFCF6",
      "shell-200": "#FBF5E9",
      "shell-300": "#F5EBDE",
      "shell-400": "#E9D8C3",
      "shell-500": "#DBC09E",
      "shell-600": "#CBAB82",
      "shell-700": "#BA9763",
      "shell-800": "#A98045",
    },
    fontFamily: {
      sans: "Circular, sans-serif",
      serif: "Canela, serif",
    },
    fontWeight: {
      thin: 200,
      light: 300,
      regular: 400,
      book: 500,
      medium: 600,
      bold: 700,
      black: 800,
    },
    letterSpacing: {
      tightest: "-.075em",
      tighter: "-.05em",
      tight: "-.02em",
      normal: "0",
      slight: ".015em",
      wide: ".025em",
      wider: ".05em",
      widest: ".1em",
    },
    strokeWidth: {
      1: "1px",
      "1/25": "1.25px",
      "1/50": "1.5px",
      "1/75": "1.75px",
      2: "2px",
      "2/25": "2.25px",
      "2/50": "2.5px",
      "2/75": "2.75px",
    },
    screens: {
      "2xs": "400px",
      xs: "475px",
      ...defaultTheme.screens,
    },
    extend: {
      animation: {
        marquee: "marquee 100s linear infinite",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translate3d(0, 0, 0)" },
          "100%": { transform: "translate3d(-50%, 0, 0)" },
        },
      },
      transitionProperty: {
        height: "height",
        "max-height": "max-height",
        spacing: "margin, padding",
        "transform-opacity": "transform, opacity",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/typography")],
};
